# Apple Sales

In [1]:
import pandas as pd

### 1. Data Overview

In [2]:
# Load the dataset
apple_sales_df = pd.read_csv('../csv_files/apple_global_sales_original.csv')

# Inspecting the first 5 rows
apple_sales_df.head()

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,APPL-00000001,2022-01-03,2022,Q1,January,Argentina,South America,Buenos Aires,AirPods (3rd Gen),AirPods,...,ARS,907.0,134344.84,Third-Party Retailer,Cash,Government,45–54,NaN,4.1,Kept
1,APPL-00000002,2022-01-04,2022,Q1,January,Argentina,South America,Buenos Aires,USB-C Woven Charge Cable,Accessories,...,ARS,907.0,115597.15,Authorized Reseller,Debit Card,Business,45–54,NaN,4.8,Kept
2,APPL-00000003,2022-05-18,2022,Q2,May,Argentina,South America,Buenos Aires,Apple Watch Series 8,Apple Watch,...,ARS,907.0,1066341.76,Corporate / B2B,Credit Card,Individual,18–24,NaN,4.3,Kept
3,APPL-00000004,2022-05-23,2022,Q2,May,Argentina,South America,Buenos Aires,MacBook Pro 14-inch (M3),Mac,...,ARS,907.0,3506044.78,Carrier Store,Credit Card,Education,45–54,NaN,NaN,Kept
4,APPL-00000005,2022-07-13,2022,Q3,July,Argentina,South America,Buenos Aires,Apple Watch Ultra 2,Apple Watch,...,ARS,907.0,1952780.07,Apple Store,Net Banking,Education,18–24,NaN,NaN,Kept

In [3]:
# Show the shape of our dataset (rows, columns)
apple_sales_df.shape

(11500, 27)

In [4]:
# Show info about our dataset
apple_sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sale_id                 11500 non-null  object
 1   sale_date               11500 non-null  object
 2   year                    11500 non-null  int64
 3   quarter                 11500 non-null  object
 4   month                   11500 non-null  object
 5   country                 11500 non-null  object
 6   region                  11500 non-null  object
 7   city                    11500 non-null  object
 8   product_name            11500 non-null  object
 9   category                11500 non-null  object
 10  storage                 6696 non-null   object
 11  color                   11500 non-null  object
 12  unit_price_usd          11500 non-null  float64
 13  discount_pct            11500 non-null  int64
 14  units_sold              11500 non-null  int64
 15  discounted_price_usd    11500 non-null  float64
 16  revenue_usd             11500 non-null  float64
 17  currency                11500 non-null  object
 18  fx_rate_to_usd          11500 non-null  float64
 19  revenue_local_currency  11500 non-null  float64
 20  sales_channel           11500 non-null  object
 21  payment_method          11500 non-null  object
 22  customer_segment        11500 non-null  object
 23  customer_age_group      11500 non-null  object
 24  previous_device_os      3444 non-null   object
 25  customer_rating         8140 non-null   float64
 26  return_status           11500 non-null  object
dtypes: float64(6), int64(3), object(18)
memory usage: 2.4+ MB

The dataset contains apple sales data, including customer information, geographic datails and product specifications.

In [5]:
# Show major aggregations
apple_sales_df.describe()

,year,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,fx_rate_to_usd,revenue_local_currency,customer_rating
count,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,1.150000e+04,8140.000000
mean,2022.997304,807.851191,3.841565,2.023478,777.365478,1568.319065,1029.406647,1.464369e+06,4.000934
std,0.821747,1112.437595,4.783161,1.443599,1072.915122,2839.759822,4072.334957,9.941160e+06,0.575192
min,2022.000000,26.690000,0.000000,1.000000,22.730000,23.000000,0.790000,2.130000e+01,3.000000
25%,2022.000000,180.147500,0.000000,1.000000,178.297500,305.740000,0.920000,1.041693e+03,3.500000
50%,2023.000000,593.905000,2.000000,1.000000,573.420000,833.040000,7.240000,6.164160e+03,4.000000
75%,2024.000000,958.387500,7.000000,3.000000,928.567500,1748.360000,91.500000,7.471653e+04,4.500000
max,2024.000000,7551.010000,15.000000,8.000000,7551.010000,59529.520000,24500.000000,5.075175e+08,5.000000

In [6]:
# Check for missing values
apple_sales_df.isnull().sum()

sale_id                      0
sale_date                    0
year                         0
quarter                      0
month                        0
country                      0
region                       0
city                         0
product_name                 0
category                     0
storage                   4804
color                        0
unit_price_usd               0
discount_pct                 0
units_sold                   0
discounted_price_usd         0
revenue_usd                  0
currency                     0
fx_rate_to_usd               0
revenue_local_currency       0
sales_channel                0
payment_method               0
customer_segment             0
customer_age_group           0
previous_device_os        8056
customer_rating           3360
return_status                0
dtype: int64

The dataset has some missing values in the following columns: storage, previous_device_os and customer rating.

We will handle it later in this notebook.

In [7]:
# Check for duplicated rows
apple_sales_df.duplicated().sum()

np.int64(0)

The dataset has no duplicates rows.

In [8]:
# Check for data types
apple_sales_df.dtypes

sale_id                    object
sale_date                  object
year                        int64
quarter                    object
month                      object
country                    object
region                     object
city                       object
product_name               object
category                   object
storage                    object
color                      object
unit_price_usd            float64
discount_pct                int64
units_sold                  int64
discounted_price_usd      float64
revenue_usd               float64
currency                   object
fx_rate_to_usd            float64
revenue_local_currency    float64
sales_channel              object
payment_method             object
customer_segment           object
customer_age_group         object
previous_device_os         object
customer_rating           float64
return_status              object
dtype: object

### 2. Data Preparation

In [9]:
# Transform the sale_date type column into datetime
apple_sales_df['sale_date'] = pd.to_datetime(apple_sales_df['sale_date'])

In [10]:
# Check if revenue match calculations
(apple_sales_df['revenue_usd'] == (apple_sales_df['units_sold'] * apple_sales_df['discounted_price_usd']).round(2)).value_counts()

True    11500
Name: count, dtype: int64

All the rows has been verified, the revenue calculations are right.

* Handling missing values

In [11]:
# Replacing the NaN values in storage and previous device os columns by 'Unknown'
apple_sales_df['storage'] = apple_sales_df['storage'].fillna('Unknown')
apple_sales_df['previous_device_os'] = apple_sales_df['previous_device_os'].fillna('Unknown')

Missing values in customer_rating are preserved as NaN to avoid introducing bias.

### 3. Creating additional columns

* Season Column

In [12]:
# Get the season from the date
def get_season(date):
    month = date.month
    day = date.day

    if (month==3 and day>=21) or (month==4 or month==5) or (month==6 and day<21):
        return 'Spring'
    elif (month==6 and day>=21) or (month==7 or month==8) or (month==9 and day<23):
        return 'Summer'
    elif (month==9 and day>=23) or (month==10 or month==11) or (month==12 and day<21):
        return 'Fall'
    else:
        return 'Winter'
    
# Creating the season column
apple_sales_df['season'] = apple_sales_df['sale_date'].apply(get_season)

# Inserting it in the dataset
apple_sales_df.insert(4, "season", apple_sales_df.pop("season"))

* Discount Amount Column

In [13]:
# Creating the discount amount column
apple_sales_df["discount_amount"] = apple_sales_df['unit_price_usd'] - apple_sales_df['discounted_price_usd']

# Inserting it in the dataset
apple_sales_df.insert(15, "discount_amount", apple_sales_df.pop("discount_amount"))

* Discount Level column

In [14]:
# Creating the discount level column
apple_sales_df['discount_level'] = pd.cut(
    apple_sales_df['discount_pct'],
    bins=[-0.1, 0, 5, 10, 15],
    labels=['No Discount', 'Low', 'Medium', 'High']
)

# Inserting it in the dataset
apple_sales_df.insert(16, 'discount_level', apple_sales_df.pop('discount_level'))

* Year-Month Column

In [15]:
# Creating the month-year column
apple_sales_df['year_month'] = apple_sales_df['sale_date'].dt.to_period('M')

# Inserting it in the table
apple_sales_df.insert(6, 'year_month', apple_sales_df.pop('year_month'))

### 4. Transform our cleaned dataframe to a csv file

In [16]:
# Last check of our dataset
apple_sales_df.head(10)

,sale_id,sale_date,year,quarter,season,month,year_month,country,region,city,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,APPL-00000001,2022-01-03,2022,Q1,Winter,January,2022-01,Argentina,South America,Buenos Aires,...,ARS,907.0,134344.84,Third-Party Retailer,Cash,Government,45–54,Unknown,4.1,Kept
1,APPL-00000002,2022-01-04,2022,Q1,Winter,January,2022-01,Argentina,South America,Buenos Aires,...,ARS,907.0,115597.15,Authorized Reseller,Debit Card,Business,45–54,Unknown,4.8,Kept
2,APPL-00000003,2022-05-18,2022,Q2,Spring,May,2022-05,Argentina,South America,Buenos Aires,...,ARS,907.0,1066341.76,Corporate / B2B,Credit Card,Individual,18–24,Unknown,4.3,Kept
3,APPL-00000004,2022-05-23,2022,Q2,Spring,May,2022-05,Argentina,South America,Buenos Aires,...,ARS,907.0,3506044.78,Carrier Store,Credit Card,Education,45–54,Unknown,NaN,Kept
4,APPL-00000005,2022-07-13,2022,Q3,Summer,July,2022-07,Argentina,South America,Buenos Aires,...,ARS,907.0,1952780.07,Apple Store,Net Banking,Education,18–24,Unknown,NaN,Kept
5,APPL-00000006,2022-07-31,2022,Q3,Summer,July,2022-07,Argentina,South America,Buenos Aires,...,ARS,907.0,280317.42,Apple Store,Cash,Education,55+,Unknown,4.9,Kept
6,APPL-00000007,2022-08-01,2022,Q3,Summer,August,2022-08,Argentina,South America,Buenos Aires,...,ARS,907.0,1762836.13,Apple Store,Gift Card,Government,35–44,Unknown,3.6,Kept
7,APPL-00000008,2022-08-04,2022,Q3,Summer,August,2022-08,Argentina,South America,Buenos Aires,...,ARS,907.0,7579762.72,Carrier Store,Gift Card,Education,25–34,iOS 16,4.7,Kept
8,APPL-00000009,2023-01-14,2023,Q1,Winter,January,2023-01,Argentina,South America,Buenos Aires,...,ARS,907.0,892415.44,Authorized Reseller,Gift Card,Government,18–24,Unknown,4.7,Kept
9,APPL-00000010,2023-01-26,2023,Q1,Winter,January,2023-01,Argentina,South America,Buenos Aires,...,ARS,907.0,471685.35,Third-Party Retailer,Apple Pay,Business,25–34,Unknown,3.6,Kept

In [17]:
# Get the csv file
apple_sales_df.to_csv("../csv_files/apple_global_sales_cleaned.csv", index=False)